main: me.dzyre.Main.Main
name: MyModd
version: Beta 1.0
api-version: 1.19
author: Dzyre

commands:
  eco:
    usage: /<command>
  bal:
    usage: /<command>
    aliases: [balance]
  pay:
    usage: /<command>
  shop:
    usage: /<command>
  backpack:
    usage: /<command>
    aliases: [bp]